timeout: 3

/nv0ken_linux
    comment: nv0ken linux
    protocol: limine
    path: boot():/kernel.elf
    cmdline: root=/dev/sda quiet

    framebuffer/width: 1280
    framebuffer/height: 720
    framebuffer/bpp: 32