#ifndef NV0KEN_DRIVERS_PCI_IDS_H
#define NV0KEN_DRIVERS_PCI_IDS_H

#define PCI_VENDOR_REALTEK 0x10ec
#define PCI_DEVICE_RTL8139 0x8139

#define PCI_CLASS_STORAGE 0x01
#define PCI_CLASS_NETWORK 0x02
#define PCI_CLASS_DISPLAY 0x03
#define PCI_CLASS_BRIDGE  0x06

#define PCI_SUBCLASS_IDE  0x01
#define PCI_SUBCLASS_ETHERNET 0x00

#endif
